### ISSUE TITLE
Errors compiling with GWT 2.8.0-rc1

### ISSUE THREAD

**Issue by kmthinkingrock** [realityforge/gwt-websockets#6]
I am getting errors while trying to use this module:

[INFO]    Tracing compile failure path for type 'org.realityforge.gwt.websockets.client.WebSocketListenerAdapter'
[INFO]       [ERROR] Errors in 'org/realityforge/gwt/websockets/client/WebSocketListenerAdapter.java'
[INFO]          [ERROR] Line 52: Nonnull cannot be resolved to a type
[INFO]          [ERROR] Line 25: Nonnull cannot be resolved to a type
[INFO]          [ERROR] Line 4: The import javax.annotation.Nonnull cannot be resolved
[INFO]          [ERROR] Line 36: Nonnull cannot be resolved to a type
[INFO]          [ERROR] Line 5: The import javax.annotation.Nullable cannot be resolved
[INFO]          [ERROR] Line 17: Nonnull cannot be resolved to a type
[INFO]          [ERROR] Line 28: Nullable cannot be resolved to a type
[INFO]          [ERROR] Line 44: Nonnull cannot be resolved to a type
[INFO]    [ERROR] Hint: Check the inheritance chain from your module; it may not be inheriting a required module or a module may not be adding its source path entries properly

I can't rebuild the module myself because I don't have the necessary build tools.

**Comment by yannyann** [comment]
I have the same issue

**Comment by realityforge** [comment]
Sorry I missed this issue. This is because you do not have a jar in the gwt compile path that includes those annotations. These can be retrieved from a number of different maven artifacts but the one that the project is compiled with is `javax_annotation: com.google.code.findbugs:jsr305:jar:2.0.1` although any will do. As they just need to be resolvable by compiler but are not used by the gwt compiler at all.
